<a href="https://colab.research.google.com/github/rubaiyat-sholi/Pickle-and-Joblib/blob/main/pickle_and_Joblib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install joblib

In [ ]:
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt
from sklearn import linear_model
import joblib

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/ML_practise_project/homeprices.csv")

In [ ]:
df.head

<bound method NDFrame.head of    area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000>

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df[['area']],df.price)

LinearRegression()

In [ ]:
reg.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

Pickle allows you to serialize your python object into a file

In [ ]:
with open('reg_pickle','wb') as f:
     pickle.dump(reg,f)

In [ ]:
with open('reg_pickle','rb') as f:
     rp = pickle.load(f)

In [ ]:
rp.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

Joblib can be a replacement of pickle (dump & load), which is more efficient on objects that carry large numpy arrays 

In [ ]:
joblib.dump(reg,"reg_joblib")

['reg_joblib']

In [ ]:
rj = joblib.load("reg_joblib")

In [ ]:
rj.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

After applying Regression here Pickle,Joblib gave the same prediction result